### ISSUE TITLE
gh-release-watch.com still emailing?

### ISSUE THREAD

**Issue by command-tab** [mystor/gh-release-watch#8]
Greetings!

I added a whole bunch of repos I'd like to be notified about to gh-release-watch.com using this GitHub account, and several of them have had releases since I set it up, but I have not received any release notifications. Is email still being dispatched successfully?

I've double-checked the email address the site should be sending to, and that the messages are not being routed to Gmail's Spam (or any other) folder.

Thanks for the excellent project!

**Comment by mystor** [comment]
I think that we are still emailing, the problem might be due to #1 (which #7 should fix once I get around to merging it).

**Comment by leipert** [comment]
Thank you for your service first of all, it's normally working great ;)

But I have the same problem, and didn't recieve a notification for the last versions of four to seven versions of [atom/atom](https://github.com/atom/atom).

**Comment by leipert** [comment]
Could we do anything to support merging of the PR #7?

I would even buy you a beer :+1:

**Comment by vapier** [comment]
seems to severely impact the usefulness of the service :/

**Comment by mystor** [comment]
I'll try to land it today - sorry for the delay.

**Comment by mystor** [comment]
#7 has been merged and deployed - hopefully everything is fixed now :)

**Comment by leipert** [comment]
Unfortunately I did not receive any mail regarding the [atom/atom](https://github.com/atom/atom) releases 1.0.17 and 1.0.18 which were both just released today.

**Comment by mystor** [comment]
I'm still receiving emails occasionally - so it hasn't broken completely AFAICT. Not sure why it isn't working for you.

**Comment by mikhoul** [comment]
Same here ----> ![http://i.imgur.com/whBuHSZ.png](http://i.imgur.com/whBuHSZ.png)

Lot of new releases but did not receive any email :disappointed:

**Comment by commandtab** [comment]
Getting release notifications via https://sibbell.com has been working for me in the meantime. I like the more straightforward feature set of gh-release-watch, though.

**Comment by mikhoul** [comment]
Thanks a lot @commandtab  it will be helpful to wait untill gh-release-watch email are back.

**Comment by nebelpfade** [comment]
didn't email anything to my gmail account

**Comment by sschuberth** [comment]
Same here. I started using the service only beginning this year, and I didn't receive mails for git-for-windows/git releases in the meantime.
